# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: org.h2.Driver
    # the username
    user: admin
    # the password
    password: root
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:h2:mem:test
    properties:
        hibernate.dialect: org.hibernate.dialect.H2Dialect
        hibernate.hbm2ddl.auto: create-drop
        show_sql: true
    
#template: Hello, %s!
#defaultName: Comeon